Newproject/Controllers/AuthorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newproject.Data;
using Newproject.Models;
using System.Linq;

namespace Demo.Controllers
{
    public class AuthorController : Controller
    {
        private ApplicationDbContext context;
        public AuthorController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }
        public IActionResult Index()
        {
            return View(context.Author.ToList());
        }
        public IActionResult Detail(int id)
        {
            var author = context.Author.Include(c => c.Book)      //Author - Book: 1 - M  
                                         .FirstOrDefault(c => c.Id == id);
            /* Note:
             * Nếu 2 bảng có kết nối trực tiếp (đi thẳng) thì dùng hàm Include
             * Nếu 2 bảng có kết nối gián tiếp (đi vòng) thông qua bảng trung gian thì dùng hàm ThenInclude
             */
            return View(author);
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var author = context.Author.Find(id);
            context.Author.Remove(author);
            context.SaveChanges();
            TempData["Message"] = "Delete author successfully !";
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "StoreOwner")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "StoreOwner")]
        [HttpPost]
        public IActionResult Create(Author author)
        {
            if (ModelState.IsValid)
            {
                context.Author.Add(author);
                context.SaveChanges();
                TempData["Message"] = "Create author successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var author = context.Author.Find(id);
            return View(author);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(Author author)
        {
            if (ModelState.IsValid)
            {
                context.Author.Update(author);
                context.SaveChanges();
                TempData["Message"] = "Edit author successfully !";
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }
    }
}

Newproject/Controllers/BookController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newproject.Data;
using Newproject.Models;
using System.Data;
using System.Linq;
using System.Reflection;

namespace Demo.Controllers
{
    public class BookController : Controller
    {

        //khai báo ApplicationDbContext để truy xuất và thay đổi dữ liệu của bảng
        private ApplicationDbContext context;
        public BookController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        //load toàn bộ dữ liệu của bảng  
        //[Authorize(Roles = "Admin")]
        /*
        public IActionResult Index()
        {
            //xếp book mới được hiển thị ở đầu danh sách (sort id giảm dần)
            var books = context.Book.OrderByDescending(m => m.Id).ToList();
            return View(books);
        }
        */
        public IActionResult Index()
        {
            return View(context.Book.ToList());
        }

        [Authorize(Roles = "Customer")]
        //hiển thị giao diện dạng card cho khách hàng order sản phẩm


        //xoá dữ liệu từ bảng
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var book = context.Book.Find(id);
            context.Book.Remove(book);
            context.SaveChanges();
            TempData["Message"] = "Delete book successfully !";
            return RedirectToAction("Index");
        }

        //xem thông tin theo id
        //[Authorize(Roles = "Admin, Customer")]
        public IActionResult Detail(int id)
        {
            var book = context.Book.Include(m => m.Category)  //Book  - Category : 1 - M
                                       .Include(b => b.Author)  //Book - Author : M - 1
                                       .FirstOrDefault(b => b.Id == id);
            return View(book);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            //đẩy danh sách của country sang bảng Add book
            ViewBag.Authors = context.Author.ToList();
            ViewBag.Brands = context.Category.ToList();
            return View();
        }

        //hàm 2: nhận và xử lý dữ liệu được gửi từ form
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(Book book)
        {
            //check tính hợp lệ của dữ liệu 
            if (ModelState.IsValid)
            {
                //add dữ liệu vào DB
                context.Book.Add(book);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Add book successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(book);
        }


        //sửa dữ liệu của bảng
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Authors = context.Author.ToList();
            ViewBag.Brands = context.Category.ToList();
            return View(context.Book.Find(id));
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(Book book)
        {
            //check tính hợp lệ của dữ liệu 
            if (ModelState.IsValid)
            {
                //update dữ liệu vào DB
                context.Update(book);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Edit book successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(book);
        }
        /*
        public IActionResult PriceAsc()
        {
            var books = context.Book.OrderBy(m => m.Price).ToList();
            return View("Store", books);
        }

        public IActionResult PriceDesc()
        {
            var books = context.Book.OrderByDescending(m => m.Price).ToList();
            return View("Store", books);
        }

        [HttpPost]
        public IActionResult Search(string keyword)
        {
            var books = context.Book.Where(m => m.Name.Contains(keyword)).ToList();
            return View("Store", books);
        }
        */
        public IActionResult Shop()
        {
            return View(context.Book.ToList());
        }
    }
}

Newproject/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newproject.Data;
using Newproject.Models;
using System.Data;
using System.Linq;

namespace Demo.Controllers
{
    public class CategoryController : Controller
    {
        //khai báo ApplicationDbContext để truy xuất và thay đổi dữ liệu của bảng
        private ApplicationDbContext context;
        public CategoryController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        //load toàn bộ dữ liệu của bảng  
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(context.Category.ToList());
        }

        //xoá dữ liệu từ bảng
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var category = context.Category.Find(id);
            context.Category.Remove(category);
            context.SaveChanges();
            TempData["Message"] = "Delete Category successfully !";
            return RedirectToAction("Index");
        }

        //xem thông tin theo id
        [Authorize(Roles = "Admin")]
        public IActionResult Detail(int id)
        {
            var category = context.Category.Include(b => b.Books)  //Brand - Mobile : 1 - M
                                       //Brand - Country : M - 1
                                     .FirstOrDefault(b => b.Id == id);
            return View(category);
        }

        //thêm dữ liệu vào bảng
        //hàm 1: render ra view
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            //đẩy danh sách của country sang bảng Add Brand
            //ViewBag.Countries = context.Author.ToList();
            return View();
        }

        //hàm 2: nhận và xử lý dữ liệu được gửi từ form
        [HttpPost]
        public IActionResult Create(string n)
        {
            //check tính hợp lệ của dữ liệu 
            var category = new Category();
            if (ModelState.IsValid)
            {
                //add dữ liệu vào DB
                category.Name = n;
                context.Add(category);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Add brand successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(category);
        }

        //sửa dữ liệu của bảng
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            //ViewBag.Countries = context.Category.ToList();
            return View(context.Category.Find(id));
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Edit(Category category)
        {
            //check tính hợp lệ của dữ liệu 
            if (ModelState.IsValid)
            {
                //update dữ liệu vào DB
                context.Update(category);
                context.SaveChanges();
                //hiển thị thông báo thành công về view
                TempData["Message"] = "Edit brand successfully !";
                //quay ngược về trang index
                return RedirectToAction(nameof(Index));
            }
            //nếu dữ liệu không hợp lệ thì trả về form để nhập lại
            return View(category);
        }
    }
}

Newproject/Controllers/RequestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newproject.Data;
using Newproject.Models;
using System.Linq;

namespace Assignment.Controllers
{

    public class RequestController : Controller
    {
        private ApplicationDbContext context;
        public RequestController(ApplicationDbContext applicationDbContext)
        {
            context = applicationDbContext;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(context.Requests.ToList());
        }


        [Authorize(Roles = "StoreOwner")]
        [HttpGet]
        public IActionResult MakeRequest()
        {

            return View();
        }

        [Authorize(Roles = "StoreOwner")]
        [HttpPost]
        public IActionResult MakeRequest(Request request)
        {
            if (ModelState.IsValid)
            {
                request.Status = false;
                context.Add(request);
                context.SaveChanges();

                return RedirectToAction(nameof(MakeRequest));
            }
            return View(request);
        }

        //delete the request
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int id)
        {
            var request = context.Requests.Find(id);
            context.Requests.Remove(request);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //display all requests
        [Authorize(Roles = "Admin")]
        public IActionResult DisplayRequests()
        {
            return View(context.Requests.ToList());
        }
    }
}

Newproject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://media.istockphoto.com/vectors/open-book-color-vector-template-icon-vector-id1197901679?k=20&m=1197901679&s=612x612&w=0&h=QjmxcWwrj_D_IHgwt-9dvAdChyI1Vtr8bmQquYVkLE4=" width="100" height="100" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Order" asp-action="Index">Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Request" asp-action="Index">Request</a>
                            </li>
                        </ul>
                    }
                    else if (User.Identity.IsAuthenticated && User.IsInRole("Customer"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="h3 text text-primary" asp-area="" asp-controller="Book" asp-action="Store">Store</a>
                            </li>
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Order" asp-action="IndexForCurrent">Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
                            </li>
                        </ul>
                    }
                    else if (User.Identity.IsAuthenticated && User.IsInRole("StoreOwner"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="h3 text text-primary" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                            </li>
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Author" asp-action="Index">Author</a>
                            </li>
                            <li class="nav-item">
                                <a class="h3 text text-success ml-3" asp-area="" asp-controller="Request" asp-action="MakeRequest">Request</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>